[package]
name = "guessing_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5" # 0.8.5 is actually shorthand for ^0.8.5 which means any version >= 0.8.5 but < 0.9.0
